"""
Scans all problem-specific README.md and notes.md files and writes:
  docs/index.md  -- markdown table grouped by platform
  docs/index.csv -- flat CSV with all fields

Run from any directory; uses file-relative paths internally.
Skips silently when not on the main branch.
"""
from __future__ import annotations

import csv
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PROBLEMS_DIR = REPO_ROOT / "problems"
INDEX_MD = REPO_ROOT / "docs" / "index.md"
INDEX_CSV = REPO_ROOT / "docs" / "index.csv"

PLATFORM_ORDER = ["leetcode", "stratascratch", "excelbi", "edna", "challenges"]


def current_branch() -> str:
    result = subprocess.run(
        ["git", "branch", "--show-current"],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    return result.stdout.strip()


def parse_frontmatter(path: Path) -> dict[str, str]:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return {}
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}
    fm: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fm[key.strip()] = value.strip().strip('"').strip("'")
    return fm


def clean_list(value: str) -> str:
    """Strip YAML list brackets: '[python, sql]' -> 'python, sql'."""
    return value.strip("[]").strip()


def detect_languages(folder: Path) -> str:
    langs = []
    if any(folder.glob("solution*.py")) or any(folder.glob("variations/*.py")):
        langs.append("python")
    if any(folder.glob("solution*.sql")):
        langs.append("sql")
    if any(folder.glob("solution*.pq")):
        langs.append("pq")
    return ", ".join(langs)


def collect_standalone(platform: str) -> list[dict]:
    platform_dir = PROBLEMS_DIR / platform
    if not platform_dir.exists():
        return []

    records = []
    for readme in sorted(platform_dir.rglob("README.md")):
        fm = parse_frontmatter(readme)
        if fm.get("platform", "") != platform:
            continue

        folder = readme.parent
        notes_fm = parse_frontmatter(folder / "notes.md")

        lang_raw = notes_fm.get("language", "")
        language = clean_list(lang_raw) if lang_raw else detect_languages(folder)

        records.append({
            "platform": platform,
            "id": fm.get("problem_id", ""),
            "slug": fm.get("slug", folder.name),
            "difficulty": fm.get("difficulty", "null"),
            "language": language,
            "topics": clean_list(notes_fm.get("topics", "")),
            "date_solved": notes_fm.get("date_solved", ""),
            "dataset": fm.get("dataset", "none"),
            "link": fm.get("link", ""),
            "path": str(folder.relative_to(REPO_ROOT)).replace("\\", "/"),
        })
    return records


def collect_challenges() -> list[dict]:
    challenges_dir = PROBLEMS_DIR / "challenges"
    if not challenges_dir.exists():
        return []

    records = []
    for notes_path in sorted(challenges_dir.rglob("notes.md")):
        folder = notes_path.parent
        # Only q## folders have notes.md -- skip challenge-root folders
        if not re.match(r"q\d+", folder.name):
            continue

        fm = parse_frontmatter(notes_path)
        challenge_fm = parse_frontmatter(folder.parent / "README.md")

        lang_raw = fm.get("language", "")
        language = clean_list(lang_raw) if lang_raw else detect_languages(folder)
        source = folder.parent.parent.name
        challenge = folder.parent.name
        q_num = folder.name.split("_")[0]

        records.append({
            "platform": "challenges",
            "id": f"{source}/{challenge}/{q_num}",
            "slug": fm.get("slug", "_".join(folder.name.split("_")[1:])),
            "difficulty": "null",
            "language": language,
            "topics": clean_list(fm.get("topics", "")),
            "date_solved": fm.get("date_solved", ""),
            "dataset": challenge_fm.get("dataset", ""),
            "link": challenge_fm.get("link", ""),
            "path": str(folder.relative_to(REPO_ROOT)).replace("\\", "/"),
        })
    return records


def write_markdown(records: list[dict]) -> None:
    total = len(records)
    by_platform: dict[str, list[dict]] = {}
    for r in records:
        by_platform.setdefault(r["platform"], []).append(r)

    lines = [
        "# Problem Index",
        "",
        "Auto-generated by `.claude/hooks/build_index.py` -- do not edit manually.",
        "",
        f"Last updated: {date.today().isoformat()}  |  Total: {total}",
        "",
        "---",
        "",
    ]

    for platform in PLATFORM_ORDER:
        if platform not in by_platform:
            continue
        rows = by_platform[platform]
        lines.append(f"## {platform.capitalize()} ({len(rows)})")
        lines.append("")
        lines.append("| ID / Ref | Slug | Difficulty | Language | Date Solved | Link |")
        lines.append("|---|---|---|---|---|---|")
        for r in rows:
            ref = r["id"] or "-"
            slug_cell = f"[{r['slug']}]({r['path']})"
            diff = r["difficulty"] if r["difficulty"] != "null" else "-"
            date_s = r["date_solved"] or "-"
            link_cell = f"[link]({r['link']})" if r["link"] else "-"
            lines.append(
                f"| {ref} | {slug_cell} | {diff} | {r['language'] or '-'}"
                f" | {date_s} | {link_cell} |"
            )
        lines.append("")

    INDEX_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {INDEX_MD.relative_to(REPO_ROOT)}")


def write_csv(records: list[dict]) -> None:
    fields = [
        "platform", "id", "slug", "difficulty", "language", "topics",
        "date_solved", "dataset", "link", "path",
    ]
    with INDEX_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(records)
    print(f"Written: {INDEX_CSV.relative_to(REPO_ROOT)}")


def main() -> None:
    branch = current_branch()
    if branch != "main":
        print(f"Skipping index rebuild (on '{branch}', not 'main')")
        sys.exit(0)

    records: list[dict] = []
    for platform in ["leetcode", "stratascratch", "excelbi", "edna"]:
        records.extend(collect_standalone(platform))
    records.extend(collect_challenges())

    if not records:
        print("No problems found -- index not updated")
        sys.exit(0)

    write_markdown(records)
    write_csv(records)
    print(f"Index rebuilt: {len(records)} problems indexed")


if __name__ == "__main__":
    main()
